apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service-deployment
spec:
  selector:
    matchLabels:
      app: subscription-service
  replicas: 2
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
      - name: subscription-service
        image: colinbut/subscription-service:1.0.0
        ports:
        - containerPort: 8080