apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service-deployment
spec:
  selector:
    matchLabels:
      app: reporting-service
  replicas: 2
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: colinbut/reporting-service:1.0.0
        ports:
        - containerPort: 8080