apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 3
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: colinbut/email-service:1.0.0
        ports:
        - containerPort: 8080