apiVersion: v1
kind: Service
metadata:
    labels:
        app: user-service
    name: user-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-service
    
