apiVersion: apps/v1
kind: Deployment
metadata:
  name: exclusion-service-deployment
spec:
  selector:
    matchLabels:
      app: exclusion-service
  replicas: 2
  template:
    metadata:
      labels:
        app: exclusion-service
    spec:
      containers:
      - name: exclusion-service
        image: colinbut/exclusion-service:1.0.0
        ports:
        - containerPort: 8080