apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  selector:
    matchLabels:
      app: account-service
  replicas: 2
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: colinbut/account-service:1.0.0
        ports:
        - containerPort: 8080