apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service-deployment
spec:
  selector:
    matchLabels:
      app: audit-service
  replicas: 2
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: colinbut/audit-service:1.0.0
        ports:
        - containerPort: 8080